version: '3.4'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672

  publisher:
    image: ${DOCKER_REGISTRY-}publisher
    build:
      context: .
      dockerfile: Publisher/Dockerfile
    ports:
      - 8082:80
    depends_on:
      - "rabbitmq"

  consumerapi1:
    image: ${DOCKER_REGISTRY-}consumerapi1
    build:
      context: .
      dockerfile: ConsumerApi1/Dockerfile
    ports:
      - 8083:80
    depends_on:
      - "publisher"

  consumerapi2:
    image: ${DOCKER_REGISTRY-}consumerapi2
    build:
      context: .
      dockerfile: ConsumerApi2/Dockerfile
    ports:
      - 8084:80
    depends_on:
      - "publisher"

  consumerapi3:
    image: ${DOCKER_REGISTRY-}consumerapi3
    build:
      context: .
      dockerfile: ConsumerApi3/Dockerfile
    ports:
      - 8085:80
    depends_on:
      - "publisher"


  consumerapi4:
    image: ${DOCKER_REGISTRY-}consumerapi4
    build:
      context: .
      dockerfile: ConsumerApi4/Dockerfile
    ports:
      - 8086:80
    depends_on:
      - "publisher"

