using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Publisher.Application.Dto
{
    public class MessageDto
    {
        [JsonIgnore]
        public string? Id { get; set; }
        /// <summary>
        /// Ski ID
        /// </summary>
        [Key]
        [Required]
        [Range(1, int.MaxValue)]
        public int SkiId { get; set; }
        /// <summary>
        /// Ski number for a product generated by system
        /// </summary>
        [Required]
        [StringLength(100, MinimumLength = 1)]
        public string SkiProductNo { get; set; }
        /// <summary>
        /// Price for pair of skis in PLN
        /// </summary>
        [Required]
        [Range(600, 6000)]
        public int PriceInPLN { get; set; }
        /// <summary>
        /// Length of pair of skis in cm
        /// </summary>
        [Required]
        [Range(110, 195)]
        public int SkiLengthInCm { get; set; }
        /// <summary>
        /// Name of ski producent
        /// </summary>
        [Required]
        [StringLength(100, MinimumLength = 1)]
        public string SkiProducent { get; set; }
    }
}
